### ISSUE TITLE
About Debug version Error

### ISSUE THREAD

**Issue by Bing1002** [andre-schulz/mve#4] opened 2016-04-26 03:12 UTC
Hi, @andre-schulz 

Recently I compiled mve on vs2015 using release version successfully. When I compiled it using debug version, it's actually Ok but when I ran it there is a error. The error information seems occur in matching. I don't know why. I will give you some snaps. Could you please have a look?

![3](https://cloud.githubusercontent.com/assets/11924213/14805573/b1bd1192-0b9f-11e6-84f0-76cf0bfe71cf.png)
![5](https://cloud.githubusercontent.com/assets/11924213/14805572/b025cfa4-0b9f-11e6-806d-09c8a2435feb.png)

**Comment by andre-schulz** [comment] 2016-04-26 12:20
Hi @tmac1002,
thanks for reporting this bug. It seems that `T tmp[8]` is aligned differently in debug vs. release mode which causes `_mm_store_si128()` to fail because it expects a pointer that is aligned on a 16-byte boundary.
You can try [this patch](https://gist.github.com/andre-schulz/e6b2fd4ff355392a275811d5714ac3da) but then `sfmrecon` crashes in `libs/sfm/bundler_incremental.cc:295`; can you confirm/reproduce that crash?

**Comment by Bing1002** [comment] 2016-04-26 12:52
Hi @andre-schulz 
 I have replace code followed by patch. But there is a new error seems like array outrange in bundle adjustment as you said.
![default](https://cloud.githubusercontent.com/assets/11924213/14818635/c2bf1200-0bf0-11e6-9156-d30d4cf93e5c.png)

.

**Comment by andre-schulz** [comment] 2016-04-26 16:11
Thanks for confirming the new bug.
It seems there's a problem with the arguments to `std::copy()`. `pose.R` is a matrix with `double` as the data type for its entries while `cam.m` uses `float`.
Please try [this patch](https://gist.github.com/andre-schulz/1abd58f421201f5e2594fa04889e559f) which should fix the new bug.

**Comment by Bing1002** [comment] 2016-04-27 00:21
Sorry, I tried it but it doesn't work and failed to compile. Do you compiled it successfully?
![1](https://cloud.githubusercontent.com/assets/11924213/14838149/02f83b52-0c51-11e6-8f7a-4edd62a6a28f.PNG)

**Comment by andre-schulz** [comment] 2016-04-27 08:56
It seems that you're using an old version of MVE. About a month ago, the Matrix and Vector classes were refactored. Please update to the latest version and try again.

**Comment by andre-schulz** [comment] 2016-04-27 15:59
I've updated my `cmake` branch with the latest fixes that were pulled into the mainline MVE repo. Both bugs should be fixed now. Please let me know if the updated code works for you or not.

**Comment by Bing1002** [comment] 2016-04-28 00:12
Yes, I've already compiled and ran it successfully. Thank you. @andre-schulz

**Comment by Bing1002** [comment] 2016-04-28 01:34
Hi @andre-schulz , now I am watching mve bebug code and I want to output the structed 3d point in sfmrecon and its color. But I haven't found a way to do it. Can you please help me? Thank you.

**Comment by andre-schulz** [comment] 2016-04-28 12:15
The cameras and the SfM points are written into the file named `synth_0.out` in the scene folder. The file is created by the function `save_photosynther_bundle()` in `libs/mve/bundle_io.cc`.

**Closed as completed** 2016-05-25 14:38 UTC
