### ISSUE TITLE
Building MVE on Windows 10

### ISSUE THREAD

**Issue by Muminpappan** [andre-schulz/mve#13] opened 2018-10-16 13:07 UTC
When I follow the instructions on https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-Windows I have some problems building MVE. When  doing cmake configure (in cmake gui) on the 3rd party folder, I get the error
_CMake Error at CMakeLists.txt:16 (message):
  32-bit builds are unsupported_
which i managed to get past by adding _CMAKE_GENERATOR_PLATFORM=x64_ (Which might not be the right solution, but it works for this part).

When I then try to build the solution using Visual Studio I get some failures, which ends in:
_========== Build: 6 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========_
The full log is to long to paste in here, but here is a .txt of it 
[log build thrid party.txt](https://github.com/andre-schulz/mve/files/2482869/log.build.thrid.party.txt)

If I then try to continue I also get some errors, mainly about not finding libjpeg (which probably is a result of the failed 3rd party build):
_CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)_

Any ideas of what might be the problem?

**Comment by andre-schulz** [comment] 2018-10-16 22:08
Hi @Muminpappan,

which Visual Studio generator did you select when you ran CMake? To avoid the error about 32-bit builds, a generator named "Visual Studio [...] **Win64**" must be used.

The problem with libjpeg is that it couldn't find `win32.mak` which is part of the Windows SDK. Can you try installing the SDK and then try compiling again?
You can get the SDK from the following URL: https://www.microsoft.com/en-us/download/details.aspx?id=8279

**Comment by Muminpappan** [comment] 2018-10-17 07:53
Hi @andre-schulz 

I did forget to use the Win64 version of Visual Studio, but it only sovled the first step, and the configure now complains directly about not finding win32.mak. The building from Visual Studio however is almost the same as before, but the problem is probably still the win32.mak.
My computer doesn't allow me to download the old windows 7 SDK that you have refered to, because it already has a newer SDK (which as I understand it does not contain the win32.mak anymore). Do I have to dig further to try to revert my SDK or use both the old and new one somehow, or is there some other way to get around the win32.mak problem? Or maybe MVE just isn't suitable for Windows versions after Windows 7?

Edit: A quick google search for "windows 7 sdk on windows 10" shows that other people seem very frustrated about not being able to solve this properly.

**Comment by andre-schulz** [comment] 2018-10-17 10:04
Hi @Muminpappan,

MVE itself should work on Windows 10. The problem is that libjpeg's build system relies on `win32.mak`. I would like to replace libjpeg with libjpeg-turbo which has a CMake-based build system which doesn't rely on `win32.mak` but I haven't gotten around to that yet.

As a workaround so you can compile libjpeg, I've uploaded `win32.mak` to GitHub. See: https://gist.github.com/andre-schulz/deb645cf320d627ce1da64ae34e76b2d
Put the file into the 3rdparty directory. Then after you have configured the 3rdparty CMake project a new variable should show up in the GUI named `WIN32_MAK_LOCATION`. Set this variable to the path where you put `win32.mak` and then configure + generate the solution and try compiling the 3rdparty project. Please let me know if this works for you.

**Comment by Muminpappan** [comment] 2018-10-17 12:41
Hi @andre-schulz 

Thanks for the win32.mak file! Unfortunately it doesn't seem to have any effect...

I downloaded your file and put it in my 3rd party folder. Then I ran cmake configure, resulting in 2 red variables popping up, "CMAKE_INSTALL_PREFIX" (which had a path already so I don't think it really was anything wrong) and the "WIN32_MAK_LOCATION" which I changed from Not found to its location in my 3rd party folder. Then I pressed configure again and the variables weren't red anymore. Then I pressed Generate which worked without any problems.
But when I then tried to build the 3rdparty.sln file it resulted in the same number of failures as before... (although not exactly the same log)
_========== Build: 6 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========_
The logfile is probably similar, but it is attached here.
[log2.txt](https://github.com/andre-schulz/mve/files/2487387/log2.txt)

**Comment by andre-schulz** [comment] 2018-10-17 13:38
Looking at the end of the log file you posted, Qt 5.5.1's configure doesn't work with paths which contain spaces. Can you try compiling in a directory which doesn't contain spaces?

Btw, if you only want to use the command-line tools and not UMVE then you can skip compiling Qt.

**Comment by Muminpappan** [comment] 2018-10-17 16:54
Thanks for noticing the spaces! I changed directory for my last try which gave that error. It fixed one error, but there is something left:
_========== Build: 7 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========_


Full log:
[log3.txt](https://github.com/andre-schulz/mve/files/2488395/log3.txt)
From what I can see, the remaining failures seems  to be connected to "gtest" or "googletest"

I actually only need the command-line tools. Does that mean that I would be able to continue to build MVE itself even if "Qt-things" fails? Or do I need to go back and skip them from the build somehow?

Super quick edit: I just saw that there was a download folder for windows 64-bit at https://www.gcc.tu-darmstadt.de/home/proj/mve/. I have no time to run any real tests until tomorrow, but at least it contains executables that I am able to run (even if I just have had time to look at their help menu for now)

**Comment by andre-schulz** [comment] 2018-10-17 17:38
You can skip gtest because the tests are currently not integrated into the CMake build system. I will update gtest to 1.8.1 which contains a fix for the error that you encountered.

> I actually only need the command-line tools. Does that mean that I would be able to continue to build MVE itself even if "Qt-things" fails? Or do I need to go back and skip them from the build somehow?

Yes, you can continue to build MVE. UMVE will be skipped if Qt is not found, so the build system will handle that case gracefully.

> Super quick edit: I just saw that there was a download folder for windows 64-bit at https://www.gcc.tu-darmstadt.de/home/proj/mve/. I have no time to run any real tests until tomorrow, but at least it contains executables that I am able to run (even if I just have had time to look at their help menu for now)

Please do not use the Win64 binaries from that page. They are over two years old and do not reflect the current state of MVE.

**Comment by Muminpappan** [comment] 2018-10-18 07:56
Thank you so much for all your help @andre-schulz !
I just finished building MVE without any more modification since my last comment and it seems to work! I havn't tested the full pipeline yet, but I can see the executables and I have run the makescene.exe on some images without any problem.

So overall it seems like my problems were:
* Using Visual Studio instead of Visual Studio Win64
* Not having win32.mak (which you then provided for me)
* Using a build path with spaces, which didn't work with Qt

**Comment by andre-schulz** [comment] 2018-10-18 11:23
> So overall it seems like my problems were:
> - Using Visual Studio instead of Visual Studio Win64
> - Not having win32.mak (which you then provided for me)
> - Using a build path with spaces, which didn't work with Qt

Yes, and also gtest 1.8.0 doesn't seem to compile with Visual Studio 2017. It seems that the `win32.mak` problem can be solved by using libjpeg-turbo and the gtest error seems it could be solved by updating to 1.8.1 which I will both look into. Maybe the Qt issue can be fixed by a newer version but that I will have to investigate.

**Closed as completed** 2018-10-29 07:25 UTC
