### ISSUE TITLE
About compile error on vs2013

### ISSUE THREAD

**Issue by Bing1002** [andre-schulz/mve#2] opened 2016-03-28 07:55 UTC
Hi, 
I have already compile 3dparty successfully on vs2013. But when I compile MVE.sln, it occured lost of error and warning. Could you help me have a look it. I will appreciate it. Thank you.
![qq 20160328155217](https://cloud.githubusercontent.com/assets/11924213/14073639/581e6126-f4fd-11e5-9391-c093eb8d29c1.jpg)

![qq 20160328155209](https://cloud.githubusercontent.com/assets/11924213/14073612/298db956-f4fd-11e5-868e-e27a90946fa5.jpg)
![qq 20160328155323](https://cloud.githubusercontent.com/assets/11924213/14073650/6bccbea2-f4fd-11e5-8906-9e21c1bde463.jpg)

**Comment by andre-schulz** [comment] 2016-03-29 11:27
Hi,
compiling MVE with Visual Studio 2013 is no longer supported because, over time, MVE will increasingly use C++11 features and Visual Studio 2013 only supports a subset of C++11. Please use Visual Studio 2015. If, for whatever reason, you have to use VS2013, try [this patch](https://gist.github.com/andre-schulz/b3a98ad52fdac8ad8912).

**Comment by Bing1002** [comment] 2016-03-30 00:25
Hi, 
Thank you for you kind answer, I try to compile it on vs2015 again. @andre-schulz

**Comment by andre-schulz** [comment] 2016-03-30 09:54
Please let me know whether you successfully compiled the code so I can close this issue.

**Comment by Bing1002** [comment] 2016-03-31 06:09
I have compiled it again  on vs2015, but I found there is also a error when compile mve_sfm. But others is ok. I post this screenshot. Can you help me look it! Thank you,
![qq 20160331140521](https://cloud.githubusercontent.com/assets/11924213/14166930/19046c16-f74a-11e5-9a81-7fcc952c174f.jpg)

**Comment by andre-schulz** [comment] 2016-03-31 11:01
Try [this patch](https://gist.github.com/andre-schulz/473021cd9a66c350a604cb68d60fb1e5).
FYI, you can make screenshots by pressing the "print screen" key and then pasting the image from the clipboard into MS Paint, for example, or any other graphics program of your choice.

**Comment by Bing1002** [comment] 2016-03-31 12:15
According to that patch, I solve the problem before, but there is a new error about _mm_popcnt_u64. The error information is identifier not found.

![default](https://cloud.githubusercontent.com/assets/11924213/14175367/2e29c4a0-f77d-11e5-82a1-a8f68af47917.png)

**Comment by andre-schulz** [comment] 2016-03-31 12:32
Hm, that is strange. This should be defined by including `nmmintrin.h` in `sfm/cascade_hashing.h`. Can you please tell me which CPU is in your computer?

**Comment by Bing1002** [comment] 2016-03-31 12:59
I have solved this problem by replace it with  _mm_popcnt_u64. I am so happy. I think because I set my vs2015 is Win32  so it unsupport u64. Besides, I found that it is forced Release version when I use cmake, I was wondering if I compile debug version so that I can debug this code. Thank you very much

**Comment by andre-schulz** [comment] 2016-03-31 13:53
Do you mean `_mm_popcnt_u32`? If yes, then beware that the code is no longer correct!
I'm curious, why are you compiling in 32-bit mode?
If you absolutely have to compile in 32-bit mode, then you can try [this patch](https://gist.github.com/andre-schulz/609a5f96d6680d9e0bf5dd9c3685205f). But I can't guarantee that this works correctly.

**Comment by Bing1002** [comment] 2016-03-31 14:09
Eh, I also think it a little strange. I only modify one place, but it actually compile successfully. By the way I 
was wondering if I can compile it using debug version. Thank you.

**Comment by andre-schulz** [comment] 2016-03-31 14:41
It does compile successfully but the code doesn't compute the correct hamming distance because it only reads the first 32 (for SURF) or 64 bits (for SIFT) instead of the full 64 (SURF) or 128 bits (SIFT).
For the code to work even remotely correctly you have to apply the patch I've linked.
Regarding compiling in debug mode: yes, you can compile MVE in debug mode. Just select the corresponding solution configuration in the dropdown menu in Visual Studio.

**Comment by Bing1002** [comment] 2016-03-31 15:03
Ok, I think I'd better compile it to 64-bits. I will try it again. When I use cmake to generate solution, it appear Focing build type to Release. I think if so when I compile it to debug using this generated solution, is there any problems or is ok. Or I can modify Cmakelist to change the build type so that I can generate Debug build type solution. I was a little confused.
Finally, I would also say thank you for your kind answers. I am really appreciative of your help.

**Comment by andre-schulz** [comment] 2016-04-01 15:33
AFAIK, when cmake creates a Visual Studio solution it doesn't force you to use any specific build type and it creates 4 build types by default (Release, Debug, RelWithDebInfo and MinSizeRel) which means you can just select the build type you want in Visual Studio and it just works without changing anything in `CMakeLists.txt`.

**Comment by tmac1002** [comment] 2016-04-04 08:51
Hi Andre,
I am sorry to bother you again. Maybe my question is so easy. I am not familiar with debuging with setting arguments by myself. so  I don't know how to set arguments so that I can debug the code. I have tried two example applications prebundle and sfmrecon. Could you help me again. I will be so thankful. @andre-schulz 
![11](https://cloud.githubusercontent.com/assets/11924213/14242946/2b8ae804-fa85-11e5-8898-f0c0506f3107.png)
![22](https://cloud.githubusercontent.com/assets/11924213/14242951/325f0caa-fa85-11e5-87ae-262bf7a248fc.png)

**Comment by Bing1002** [comment] 2016-04-04 10:05
Hi Andre,
I am sorry to bother you again, but I really hope you can help me again. When I compiled code successfully and run it, I have no idea about how to set image directory so than I can get correct results. Could you help me look at it. I'm very grateful for you.
![qq](https://cloud.githubusercontent.com/assets/11924213/14244796/ac4fe0de-fa8f-11e5-8a22-18cd8f7092bc.png)
![w](https://cloud.githubusercontent.com/assets/11924213/14244807/b9b8457c-fa8f-11e5-92ab-c41e31b7b7c2.png)

**Comment by andre-schulz** [comment] 2016-04-04 11:45
FYI, you can find an introduction on how to use the MVE pipeline [here](https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide#the-reconstruction-pipeline).
Basically, you used `sfmrecon` correctly but you have to pass a directory to `sfmrecon` which contains an MVE scene. In your case, `sfmrecon` interprets `prebundle` as a directory but it doesn't exist which is why it didn't work. To create an MVE scene, you have to run `makescene` first and then pass the directory created by `makescene` to `sfmrecon`.

**Comment by Bing1002** [comment] 2016-04-06 10:35
Hi, I think my questions maybe too much. But I really have no idea. When I compiled and built it successfully, I found it's so slow when extracting features. And when matching these feature, the program just crashed. I don't know why was that. Is this because my machine configuration or my setting error?
![111](https://cloud.githubusercontent.com/assets/11924213/14313788/36ef983c-fc26-11e5-91e9-bdca9ca95acb.png)
![22](https://cloud.githubusercontent.com/assets/11924213/14313792/3d5e97b8-fc26-11e5-9935-3423120ae009.png)

**Comment by andre-schulz** [comment] 2016-04-06 10:51
The reason why it is so slow is that you've compiled in Debug mode. Try compiling the programs in Release mode and they should be much faster. The sfmrecon crash shouldn't happen. Is the crash reproducible? Can you please send me a stack trace/the call stack when the crash happens?

**Comment by Bing1002** [comment] 2016-04-13 10:05
Hi @andre-schulz 

I have just a question, I found that in many sfm papers include MVE, they did't consider the image distortion and get distortion coefficient. I was wondering if distortion coefficient just have little influence on the process of sfm so we can only estimate focal length. If I want to include distortion coefficient, what should I do. I hope you can help me answer this doubts. Thank you.

**Comment by andre-schulz** [comment] 2016-04-13 14:32
Unfortunately, I don't know the answer to your question. But you can send an email to the MVE mailing list (mve@gris.informatik.tu-darmstadt.de) and hopefully someone can answer your question there.

**Closed as completed** 2016-04-14 11:19 UTC
